#!/bin/zsh -i
# shell has to be interactive to load modules

. "$(dirname "$(readlink -f "$0")")"/functions.zsh
what="geant4"

if [[ $# -eq 1 ]]; then
	local version=$1
else
	# error
	echo " > ERROR: No geant4 version given. Exiting."
	exit 1
fi

echo " > Installing geant4 version $geant4_version"
echo

module purge
module load sim_system
module load geant4/$geant4_version

if [[ $? -ne 0 ]]; then
	echo " > ERROR: module load geant4/$geant4_version failed. Exiting."
	exit 1
fi
echo

echo " > Checking / Installing missing dependencies for geant4 version $geant4_version"
[ "$(moduleTestResult clhep   $CLHEP_VERSION)"   -eq 0 ] && echo " > clhep $CLHEP_VERSION is installed"     || install_clhep $CLHEP_VERSION
[ "$(moduleTestResult xercesc $XERCESC_VERSION)" -eq 0 ] && echo " > xercesc $XERCESC_VERSION is installed" || install_xercesc $XERCESC_VERSION
[ "$(moduleTestResult geant4  $G4_VERSION)"      -eq 0 ] && echo " > Done with geant4 source"               || install_geant4_source
