#!/usr/bin/env zsh

# preliminary
. "$(dirname "$(readlink -f "$0")")"/functions.zsh
what="clhep"
what_version=$1
ensure_modules || whine_and_quit "ensure_modules failure"
prepare_version "$what" "$what_version" || whine_and_quit "prepare_version failure"

# clhep specific
tag="CLHEP_${CLHEP_VERSION//./_}"
url="https://gitlab.cern.ch/CLHEP/CLHEP.git"
base_dir="$CLHEP_BASE_DIR"
source_dir=$CLHEP_BASE_DIR/source
build_dir=$CLHEP_BASE_DIR/build
cmake_options="-Wno-dev -DBUILD_STATIC_LIBS=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON"

# logging and installing
log_general "$what" "$what_version" "$url" "$base_dir"
clone_tag "$url" "$tag" "$source_dir" "$what"
cmake_build_and_install "$source_dir" "$build_dir" "$base_dir" "$cmake_options" "$what"

# all done. Testing module
echo "$magenta > Testing $what installation.$reset"
module test $what/$what_version
exit $?

