#!/bin/zsh

# if the environment variables G4INSTALL and G4_VERSION are not set, exit
if [[ -z "$G4INSTALL" || -z "$G4_VERSION" ]]; then
	echo "$red > G4INSTALL or $G4_VERSION environment variables are not set. Exiting.$reset"
	exit 1
fi

what="geant4"
what_version="$G4_VERSION"
source_dir=$G4INSTALL/source
build_dir=$G4INSTALL/build
base_dir=$G4INSTALL
filename="https://gitlab.cern.ch/geant4/geant4/-/archive/v$G4_VERSION/geant4-v$G4_VERSION.tar.gz"
tar_strip=1 # in the tarball, the source is inside VERSION/CLHEP

# Full list of options and explanation:
# https://geant4-userdoc.web.cern.ch/UsersGuides/InstallationGuide/html/index.html

# assuming qmake is installed and in the path
if command -v qmake6 &> /dev/null; then
    qmake_path=$(command -v qmake6)
elif command -v qmake &> /dev/null; then
    qmake_path=$(command -v qmake)
else
    echo "Error: qmake or qmake6 not found. Please install Qt development tools."
    exit 1
fi

echo "$magenta > QMake found at: $qmake_path$reset"

cmake_gdml="  -DGEANT4_USE_GDML=ON -DXERCESC_ROOT_DIR=$XERCESCROOT -DXercesC_INCLUDE_DIR=$XERCESCROOT/include/xercesc -DXercesC_VERSION=XERCESC_VERSION"
cmake_clhep=" -DCLHEP_ROOT_DIR=$CLHEP_BASE_DIR"
cmake_qt6="   -DQT_QMAKE_EXECUTABLE=$qmake_path  -DGEANT4_USE_QT=ON -DGEANT4_USE_QT_QT6=ON"
cmake_data="  -DGEANT4_INSTALL_DATA=ON -DGEANT4_INSTALL_PACKAGE_CACHE=ON"
cmake_pack="  -DBUILD_STATIC_LIBS=ON -DGEANT4_USE_SYSTEM_EXPAT=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DGEANT4_USE_SYSTEM_ZLIB=ON"
cmake_mt="    -DGEANT4_BUILD_MULTITHREADED=ON  -DGEANT4_BUILD_BUILTIN_BACKTRACE=OFF "
x11_option=" -DGEANT4_USE_OPENGL_X11=ON -DGEANT4_USE_RAYTRACER_X11=ON "
cmake_options="$cmake_gdml $cmake_clhep $cmake_qt6 $cmake_data $cmake_pack $cmake_mt $x11_option"

#  not used
# -DCMAKE_CXX_STANDARD=20
# -DGEANT4_USE_SYSTEM_ZLIB=ON
# -DBUILD_SHARED_LIBS=OFF
# -DDGEANT4_USE_USOLIDS=ON, requires vecgeom installed
# -DGEANT4_INSTALL_PACKAGE_CACHE=OFF
# -DBUILD_SHARED_LIBS=OFF

source "$(dirname "$(readlink -f "$0")")"/functions.zsh
log_general geant4 "$G4_VERSION" "$filename" "$base_dir"
unpack_source_in_directory_from_url "$filename" "$source_dir" "$tar_strip"
cmake_build_and_install "$source_dir" "$build_dir" "$base_dir" "$cmake_options"

echo "$magenta > $what installation completed.$reset"
module test geant4/$what_version
exit $?


